data:
  training_data_path: "data/processed/training_data.csv"
  validation_data_path: "data/processed/validation_data.csv"
  test_data_path: "data/processed/test_data.csv"

  prediction_data_path: "data/processed/test_data.csv"
  target_column: "Enterococci"
  date_column: "DateTime"
  site_column: "SITE_NAME"

feature_engineering:
  rainfall_lags: [3, 6, 12, 24, 48, 72]
  wind_lags: [3, 6, 12, 24]
  tide_lags: [1, 2, 3]
  transform_target: false
  target_transform_method: "log"

models:
  probabilistic_framework:
    # quantiles: [0.05, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.975]
    # quantiles: [0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95, 0.975]
    # quantiles: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.925, 0.95, 0.975]
    quantiles: [0.20, 0.35, 0.50, 0.60, 0.70, 0.75, 0.80, 0.85, 0.90, 0.925, 0.95, 0.975]
    meta_learner: false
    calibration: true
    lgb_params:
      n_estimators: 180
      learning_rate: 0.08721057029770096
      num_leaves: 40
      min_data_in_leaf: 5
      colsample_bytree: 0.9587602766121369
      reg_lambda: 0.6540961177848345
      boosting_type: 'gbdt'
      max_bin: 211
    meta_learner_tune: False
    meta_learner_params:
      n_estimators: 100
      learning_rate: 0.1
      num_leaves: 31
      min_data_in_leaf: 20
      colsample_bytree: 0.8
      reg_lambda: 0.1
      boosting_type: 'gbdt'
      max_bin: 255

  
  matrix_decomposition_framework:
    n_components: 4
    init: 'nndsvd'
    alpha: 0.0
    l1_ratio: 0.0
    max_iter: 1000
    tol: 1e-4
    solver: 'mu'
    random_state: None
    time_model_type: "random_forest"
    space_model_type: "random_forest"
  
  benchmarks:
    linear_regression:
      alpha: 0.1
      l1_ratio: 0.5
    
    decision_tree:
      max_depth: 8
      min_samples_leaf: 40
    
    lightgbm:
      n_estimators: 200
      learning_rate: 0.05
      max_depth: 8
      num_leaves: 128
      min_data_in_leaf: 20
      bagging_fraction: 0.8
      feature_fraction: 0.8
      lambda_l1: 0.1
      lambda_l2: 0.1

evaluation:
  metrics: ["rmse", "sensitivity", "specificity", "wmape_safe", "wmape_exceedance"]
  cross_validation:
    method: "time_series_cv"
    n_splits: 3
    test_periods: ["2021-10-01_2022-10-01", "2022-10-01_2023-10-01", "2023-10-01_2024-10-01"]
  report_path: "reports/evaluation_results.json"

pipeline:
  # models_to_train: ["probabilistic_framework", "matrix_decomposition_framework", "linear_regression", "decision_tree", "lightgbm"]
  random_seed: None
  # models_to_process: ["lightgbm", "linear_regression", "decision_tree", "mlp"]
  # models_to_train: ["probabilistic_framework", "lightgbm", "matrix_decomposition_framework"]
  # models_to_process: ["probabilistic_framework", "lightgbm", "matrix_decomposition_framework"]
  models_to_train: ["probabilistic_framework"]
  models_to_process: ["probabilistic_framework"]
  # models_to_train: ["matrix_decomposition_framework"]
  # models_to_process: ["matrix_decomposition_framework"]

prediction:
  # model_name: ["probabilistic", "lightgbm", "matrix_decomposition_framework"]
  model_name: ["probabilistic_framework"]
  # model_path: "models/lightgbm.joblib"
  output_path: "results/predictions.csv"
  generate_visualizations: true
  visualization_path: "results/visualizations"
  training_prediction_data_path: "results/training_predictions.csv"

